name: Build GmsCore

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  start_building_gmscore:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list

    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Execute build script
      run: bash ./build.sh

    - name: Release Gmscore
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./prebuilt/*
        tag: ${{ github.ref }}
        overwrite: true
        body: "ReVanced GmsCore Release Synced With MicroG Services"
        file_glob: true
